import { SYSTEM_PROMPT, generateUserPrompt } from '../utils/aiPrompts';

// Mock AI Service for now. In production, use OpenAI SDK.
export class AIService {
  async generateInsights(user: any, transactions: any[]) {
    // const prompt = generateUserPrompt(transactions, user);
    
    // Simulate AI delay
    await new Promise((resolve) => setTimeout(resolve, 1500));

    // Mock Response
    const totalExpense = transactions
      .filter((t) => t.type === 'EXPENSE')
      .reduce((acc, t) => acc + t.amount, 0);

    const topCategory = this.getTopCategory(transactions);

    return `
# 🤖 AI Financial Insights

## 📊 Spending Overview
You have spent **${user.currency} ${totalExpense.toFixed(2)}** recently. 
Your highest spending category is **${topCategory}**.

## 💡 Savings Opportunities
- **Dining Out**: You spent a significant amount on food this week. Consider cooking at home 2 days more.
- **Subscriptions**: Review your recurring payments.

## 🚀 UPI Analysis
- You use UPI frequently for small payments (< ₹500). This adds up!
- **Tip**: Try to withdraw cash for small daily expenses to track them better.

## ⚠️ Budget Alert
- You are approaching your projected limit for **Shopping**. Slow down!

*Generated by AI Advisor*
    `;
  }

  private getTopCategory(transactions: any[]) {
    const categories: any = {};
    transactions.forEach((t) => {
      if (t.type === 'EXPENSE') {
        categories[t.category] = (categories[t.category] || 0) + t.amount;
      }
    });
    return Object.keys(categories).reduce((a, b) => categories[a] > categories[b] ? a : b, 'None');
  }
}

export const aiService = new AIService();
